name: Ollama Dev Server

on:
  workflow_dispatch: # Trigger manually

jobs:
  run-ollama:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
    - name: Checkout (not used but required)
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Install Ollama
      run: |
        curl -fsSL https://ollama.com/install.sh | sh
        sudo systemctl start docker
        ollama --version

    - name: Pull Open Source Coding Models
      run: |
        ollama pull deepseek-coder:6.7b
        ollama pull codellama:7b
        ollama pull mistral

    - name: Start Ollama Serve in Background
      run: |
        nohup ollama serve > ollama.log 2>&1 &

    - name: Expose Ollama via locl (or ngrok if preferred)
      run: |
        npm install -g localtunnel
        npx localtunnel --port 11434 > tunnel.log &
        sleep 10
        echo "🔗 Public URL:"
        cat tunnel.log
